// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#ifndef __BINDINGS_GREETER_ADAPTER_H
#define __BINDINGS_GREETER_ADAPTER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} greeter_adapter_string_t;

// Imported Functions from `wasmcon2023:greet/interface`
void wasmcon2023_greet_interface_greet(greeter_adapter_string_t *ret);

// Exported Functions from `wasmcon2023:greet/interface`
void exports_wasmcon2023_greet_interface_greet(greeter_adapter_string_t *ret);

// Helper Functions

void greeter_adapter_string_set(greeter_adapter_string_t *ret, const char*s);
void greeter_adapter_string_dup(greeter_adapter_string_t *ret, const char*s);
void greeter_adapter_string_free(greeter_adapter_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
