// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#include "greeter_adapter.h"


__attribute__((__import_module__("wasmcon2023:greet/interface"), __import_name__("greet")))
void __wasm_import_wasmcon2023_greet_interface_greet(int32_t);
__attribute__((__weak__, __export_name__("cabi_post_wasmcon2023:greet/interface#greet")))
void __wasm_export_exports_wasmcon2023_greet_interface_greet_post_return(int32_t arg0) {
  if ((*((int32_t*) (arg0 + 4))) > 0) {
    free((void*) (*((int32_t*) (arg0 + 0))));
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void greeter_adapter_string_set(greeter_adapter_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void greeter_adapter_string_dup(greeter_adapter_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void greeter_adapter_string_free(greeter_adapter_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

void wasmcon2023_greet_interface_greet(greeter_adapter_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasmcon2023_greet_interface_greet(ptr);
  *ret = (greeter_adapter_string_t) { (char*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

__attribute__((__export_name__("wasmcon2023:greet/interface#greet")))
int32_t __wasm_export_exports_wasmcon2023_greet_interface_greet(void) {
  greeter_adapter_string_t ret;
  exports_wasmcon2023_greet_interface_greet(&ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

extern void __component_type_object_force_link_greeter_adapter(void);
void __component_type_object_force_link_greeter_adapter_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_greeter_adapter();
}
