// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#ifndef __BINDINGS_PROXY_GREETER_H
#define __BINDINGS_PROXY_GREETER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} proxy_greeter_string_t;

// Imported Functions from `wasmcon2023:greet/interface`
void wasmcon2023_greet_interface_greet(proxy_greeter_string_t *ret);

// Exported Functions from `wasmcon2023:greet/interface`
void exports_wasmcon2023_greet_interface_greet(proxy_greeter_string_t *ret);

// Helper Functions

void proxy_greeter_string_set(proxy_greeter_string_t *ret, const char*s);
void proxy_greeter_string_dup(proxy_greeter_string_t *ret, const char*s);
void proxy_greeter_string_free(proxy_greeter_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
